[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "Gnt6RtLjNk8UvfTJEWGsx1Ay5VTJyiH3KjpsGBfuB4dh"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
solana_twitter = "2BDbYV1ocs2S1PsYnd5c5mqtdLWGf5VbCYvf28rs9LGj"

[programs.mainnet]
solana_twitter = "2BDbYV1ocs2S1PsYnd5c5mqtdLWGf5VbCYvf28rs9LGj"


[provider]
cluster = "localnet"
wallet = "/Users/docho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
